// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzUESXQRc0U-qx07R_n13ePQzGyarBwBs',
    appId: '1:110147617748:web:065c9a54ce3525ca6ecc41',
    messagingSenderId: '110147617748',
    projectId: 'qr-code-scanner-and-gene-58152',
    authDomain: 'qr-code-scanner-and-gene-58152.firebaseapp.com',
    storageBucket: 'qr-code-scanner-and-gene-58152.appspot.com',
    measurementId: 'G-8F5R3DQ21M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfAM0Bv6S_lkpq9IE_ld6CaDTLgwCOQi8',
    appId: '1:110147617748:android:a829d1d0466d3a7b6ecc41',
    messagingSenderId: '110147617748',
    projectId: 'qr-code-scanner-and-gene-58152',
    storageBucket: 'qr-code-scanner-and-gene-58152.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5DjRc4oJ1O93iCEljk658GuwY1KTCh7s',
    appId: '1:110147617748:ios:11858439313766616ecc41',
    messagingSenderId: '110147617748',
    projectId: 'qr-code-scanner-and-gene-58152',
    storageBucket: 'qr-code-scanner-and-gene-58152.appspot.com',
    iosBundleId: 'com.solinovation.qrcodescanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5DjRc4oJ1O93iCEljk658GuwY1KTCh7s',
    appId: '1:110147617748:ios:11858439313766616ecc41',
    messagingSenderId: '110147617748',
    projectId: 'qr-code-scanner-and-gene-58152',
    storageBucket: 'qr-code-scanner-and-gene-58152.appspot.com',
    iosBundleId: 'com.solinovation.qrcodescanner',
  );
}
